name: Run test 

on:
  push:
    branches:
      - 'lesson15'
  pull_request:
    branches:
      - 'lesson15'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Folder
        run: cd ./lesson15
      - name: Dependencies
        working-directory: ./lesson15
        run: npm i
      - name: Run tests
        working-directory: ./lesson15
        run: npm test
