name: Run test

on:
  push:
    branches:
      - 'lesson15'
  pull_request:
    branches:
      - 'main'

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.9.0

      - name: Install dependencies
        run: |
          npm install
          npm install jest --save-dev

      - name: Run tests
        run: npm test
